"""Frontend pidorasi4

Revision ID: 00829ca1855c
Revises: 735d2f7aef61
Create Date: 2024-04-10 23:40:08.661166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00829ca1855c'
down_revision: Union[str, None] = '735d2f7aef61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('information_user_id_key', 'information', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('information_user_id_key', 'information', ['user_id'])
    # ### end Alembic commands ###
