"""Change add ifo 2704

Revision ID: 06bc783f331f
Revises: c55a5d1812b3
Create Date: 2024-04-27 19:31:16.965085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '06bc783f331f'
down_revision: Union[str, None] = 'c55a5d1812b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('email', sa.String(), nullable=True))
    op.alter_column('information', 'technology',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('information', 'tg',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('information', 'vk',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('information', 'education',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('information', 'work',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('information', 'work',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('information', 'education',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('information', 'vk',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('information', 'tg',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('information', 'technology',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.drop_column('information', 'email')
    # ### end Alembic commands ###
