"""remont download base4

Revision ID: 31fd6d1f8d16
Revises: 8f1094193d45
Create Date: 2024-04-29 18:33:22.954802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '31fd6d1f8d16'
down_revision: Union[str, None] = '8f1094193d45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('information')
    op.drop_table('download')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tag', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='download_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='download_pkey')
    )
    op.create_table('information',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('education', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('work', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('technology', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('tg', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('vk', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='information_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='information_pkey')
    )
    # ### end Alembic commands ###
