"""Frontend pidorasi2

Revision ID: 67d53a6b1760
Revises: cfa4dca789e1
Create Date: 2024-04-10 21:55:45.804116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d53a6b1760'
down_revision: Union[str, None] = 'cfa4dca789e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
