"""Frontend pidorasi3

Revision ID: 735d2f7aef61
Revises: 67d53a6b1760
Create Date: 2024-04-10 21:57:09.346117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '735d2f7aef61'
down_revision: Union[str, None] = '67d53a6b1760'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
