"""male is allrady true3

Revision ID: 8f7cd1cee9ce
Revises: b37cd0bbea63
Create Date: 2024-04-02 03:14:58.939623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f7cd1cee9ce'
down_revision: Union[str, None] = 'b37cd0bbea63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
