"""Create work 3 base popitka 2

Revision ID: b75d6e7d2707
Revises: 8c9e3ac9ed7c
Create Date: 2024-04-29 19:18:02.828087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b75d6e7d2707'
down_revision: Union[str, None] = '8c9e3ac9ed7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
