"""Change database aut and additional info 6

Revision ID: c88bbc56a5db
Revises: ca2aa4fadfda
Create Date: 2024-04-10 04:09:00.884960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88bbc56a5db'
down_revision: Union[str, None] = 'ca2aa4fadfda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'user',
        sa.PrimaryKeyConstraint('id')
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
