"""Change database aut and additional info 5

Revision ID: ca2aa4fadfda
Revises: 32299e4652fe
Create Date: 2024-04-10 04:06:54.014665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca2aa4fadfda'
down_revision: Union[str, None] = '32299e4652fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
