"""Frontend pidorasi

Revision ID: cfa4dca789e1
Revises: e6a4d7f550c4
Create Date: 2024-04-10 21:54:32.263486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfa4dca789e1'
down_revision: Union[str, None] = 'e6a4d7f550c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
