"""basedata 1:m to dowload base3

Revision ID: d3b0cc608ec4
Revises: 3e9d62902def
Create Date: 2024-04-28 15:55:35.257672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3b0cc608ec4'
down_revision: Union[str, None] = '3e9d62902def'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
