"""update download base to m:m

Revision ID: d64abe2b0297
Revises: 803c829c3159
Create Date: 2024-04-27 19:49:15.648987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64abe2b0297'
down_revision: Union[str, None] = '803c829c3159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'download', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'download', type_='foreignkey')
    # ### end Alembic commands ###
