"""change database info

Revision ID: e4530a37b92e
Revises: 4278f1debf43
Create Date: 2024-03-31 02:49:02.188818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4530a37b92e'
down_revision: Union[str, None] = '4278f1debf43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_column('information', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('information', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('information', 'user_id')
    # ### end Alembic commands ###
